---
title: "A Script for analyzing the second Pilot's data"
author: "Aziz Abubshait"
date: "4/11/2021"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


```{r read-in data, echo = F}
pilot_path = paste(getwd(), "/pilot data/", sep = "")
list_of_datanames = list.files(pilot_path)
dat_p2 = lapply(paste(pilot_path, list_of_datanames, sep = ""), read.csv)
dat_p2 = do.call(plyr::rbind.fill, dat_p2)
```

```{r now do some data preprocessing, echo = F}
dat_clean = dat_p2 %>% 
  group_by(participant) %>% 
  # get rid of practice trials
  slice(-c(1:8)) %>% 
  # we need to recode to 1 and 2 because the fill function won't work for characters. 
  # It only works for numeric variables
  mutate(
    key_resp_2.keys = 
           case_when(key_resp_2.keys == "c" ~ 1,
                     key_resp_2.keys == "h" ~ 2)) %>% 
  fill(key_resp_2.keys, .direction = "up") %>%
  fill(key_resp_2.corr, .direction = "up") %>%
  mutate(
    choice = recode(
      key_resp_2.keys, `1` = "comp", `2` = "human")) %>%
  # remove some vars
  select(-c(9:12,18:88, 99:118, 126:137)) %>%
  ## Delete every 11th row
  filter(
    is.na(Number)==F,
    (RTLeft!=13),
    (RTRight!=13)
    ) %>%
  mutate(
    # measure synchrony
    sync_value = abs((RTLeft-RTRight))/
      (RTLeft+RTRight)*100) %>% 
  mutate(sync_z_value = scale(sync_value)) %>% 
  ungroup(participant)
```


## Here are some Plots to visualize the results\ First, is how many instances of choices do we have?
```{r, fig.height=8, fig.width=8}
dat_clean %>%
  group_by(participant, Partner) %>% 
  summarize(choice = first(choice)) %>%
  ggplot(aes(x = Partner, fill = choice))+
    geom_histogram(stat="count", position = position_dodge(.9), 
                   color = "black",
                   lwd = 1, alpha = .8)+theme_bw()+
  geom_text(stat='count', aes(label=round(..count..)), 
            position = position_dodge(.9), vjust=2) +
  labs(title = "number of choices for all participants")

dat_clean %>%
  group_by(participant, Partner) %>% 
  summarize(choice = first(choice)) %>%
  ggplot(aes(x = Partner, fill = choice))+
    geom_histogram(stat="count", position = position_dodge(.9), 
                   color = "black",
                   lwd = 1, alpha = .8)+theme_bw()+
  geom_text(stat='count', aes(label=round(..count..)), 
            position = position_dodge(.9), vjust=2) +
  facet_wrap(~participant)+
  labs(title = "number of choices for for each dyad")
```

## Next, we have the actual sync values. Sync values are calculated as percentages. The formula is\ RT_participant1 - RT_participant2 / (RT_participant1 + RT_participant2)

```{r}
dat_clean %>%
  ggplot(aes(y = sync_value, x = Partner, color = choice))+
  stat_summary(fun.data = mean_se, geom = "errorbar", 
               width = .1, position = position_dodge(.3),
               fun.args = list(mult = 1))+
  stat_summary(fun.data = mean_se, geom = "point", size = 5, 
               position = position_dodge(.3))+
  theme_bw()+
  labs("Sync valye for each agent by participant choice")

dat_clean %>%
  ggplot(aes(y = sync_value, x = choice, color = choice))+
  stat_summary(fun.data = mean_se, geom = "errorbar", 
               width = .1, position = position_dodge(.3),
               fun.args = list(mult = 1))+
  stat_summary(fun.data = mean_se, geom = "point", size = 5, 
               position = position_dodge(.3))+
  theme_bw()+
  labs("Sync valye by participant choice")

dat_clean %>%
  ggplot(aes(y = sync_value, x = Partner))+
  stat_summary(fun.data = mean_se, geom = "errorbar", 
               width = .1, position = position_dodge(.3),
               fun.args = list(mult = 1))+
  stat_summary(fun.data = mean_se, geom = "point", size = 5, 
               position = position_dodge(.3))+
  theme_bw()+
  labs("Sync valye for each actual partner")

dat_clean %>%
  ggplot(aes(y = sync_value, x = Partner, color = choice))+
  geom_point(shape = 1, alpha = .8, position = position_jitterdodge(.1))+
  stat_summary(fun.data = mean_se, geom = "errorbar", 
               width = .1, position = position_dodge(.8),
               fun.args = list(mult = 1.96))+
  stat_summary(fun.data = mean_se, geom = "point", size = 5, 
               position = position_dodge(.8))+
  theme_bw()+
  labs("Sync valye for each agent by participant choice with individual data points")
```


## Now lets look at the same data but exclude sync values beyond 6 SD.
```{r data without the points beyond 6 SD, echo = F}
## Now do some preprocessing
dat_clean2 = dat_clean %>% 
  filter(sync_z_value < 6)
```

```{r}
dat_clean2 %>%
  ggplot(aes(y = sync_value, x = Partner, color = choice))+
  stat_summary(fun.data = mean_se, geom = "errorbar", 
               width = .1, position = position_dodge(.3),
               fun.args = list(mult = 1))+
  stat_summary(fun.data = mean_se, geom = "point", size = 5, 
               position = position_dodge(.3))+
  theme_bw()+
  labs(title = "Sync value for each agent by participant choice within 6 SD")

dat_clean2 %>%
  ggplot(aes(y = sync_value, x = Partner))+
  stat_summary(fun.data = mean_se, geom = "errorbar", 
               width = .1, position = position_dodge(.3),
               fun.args = list(mult = 1))+
  stat_summary(fun.data = mean_se, geom = "point", size = 5, 
               position = position_dodge(.3))+
  theme_bw()+
  labs(title = "Sync valye for each actual partner within 6 SD")

dat_clean2 %>%
  ggplot(aes(y = sync_value, x = Partner, color = choice))+
  geom_point(shape = 1, alpha = .8, position = position_jitterdodge(.1))+
  stat_summary(fun.data = mean_se, geom = "errorbar", 
               width = .1, position = position_dodge(.8),
               fun.args = list(mult = 1.96))+
  stat_summary(fun.data = mean_se, geom = "point", size = 5, 
               position = position_dodge(.8))+
  theme_bw()+
  labs(title = "Sync valye for each agent by participant choice with individual data points within 6 SD")

```

## Percentage of "cheating"
```{r}
library(knitr)
kable(dat_clean %>%
  group_by(participant) %>%
  summarize(n_cheat = 160-length(RTLeft),
            cheat_percent = n_cheat/200*100))

kable(dat_clean %>%
  group_by(participant, Block.thisN) %>%
  summarize(n_cheat = 10-length(RTLeft),
            cheat_percent = n_cheat/10*100))

```


```{r lets try removing blocks that have more than 2 errors, echo = F}
dat_clean %>% 
  group_by(participant, Block.thisN) %>%
  mutate(good_trials_n = n()) %>%
  filter(good_trials_n > 8) %>%
  ggplot(aes(y = sync_value, x = Partner, color = choice))+
  stat_summary(fun.data = mean_se, geom = "errorbar", 
               width = .1, position = position_dodge(.3),
               fun.args = list(mult = 1))+
  stat_summary(fun.data = mean_se, geom = "point", size = 5, 
               position = position_dodge(.3))+
  theme_bw()+
  labs(title = "Exclude bad blocks (n trials >= 8)")
```

```{r Check first half of exp vs. second half}

dat_clean %>% 
  group_by(participant) %>%
    group_by(participant, Block.thisN) %>%
  mutate(good_trials_n = n()) %>%
  filter(good_trials_n > 8) %>%
  ungroup(Block.thisN) %>%
  mutate(first_sec = ifelse(Block.thisN <= 7, "First", "Second")) %>%
  ggplot(aes(y = sync_value, x = Partner))+
  stat_summary(fun.data = mean_se, geom = "errorbar", 
               width = .1, position = position_dodge(.3),
               fun.args = list(mult = 1))+
  stat_summary(fun.data = mean_se, geom = "point", size = 5, 
               position = position_dodge(.3))+
  theme_bw()+facet_wrap(~first_sec)+
  labs(title = "first vs second blocks Partner")

dat_clean %>% 
  group_by(participant) %>%
    group_by(participant, Block.thisN) %>%
  mutate(good_trials_n = n()) %>%
  filter(good_trials_n > 8) %>%
  ungroup(Block.thisN) %>%
  mutate(first_sec = ifelse(Block.thisN <= 7, "First", "Second")) %>%
  ggplot(aes(y = sync_value, x = choice, color = choice))+
  stat_summary(fun.data = mean_se, geom = "errorbar", 
               width = .1, position = position_dodge(.3),
               fun.args = list(mult = 1))+
  stat_summary(fun.data = mean_se, geom = "point", size = 5, 
               position = position_dodge(.3))+
  theme_bw()+
  labs(title = "sync value dependent on choice")


dat_clean %>% 
  group_by(participant) %>%
    group_by(participant, Block.thisN) %>%
  mutate(good_trials_n = n()) %>%
  filter(good_trials_n > 8) %>%
  ungroup(Block.thisN) %>%
  mutate(first_sec = ifelse(Block.thisN <= 7, "First", "Second")) %>%
  ggplot(aes(y = sync_value, x = Partner, color = choice))+
  stat_summary(fun.data = mean_se, geom = "errorbar", 
               width = .1, position = position_dodge(.3),
               fun.args = list(mult = 1))+
  stat_summary(fun.data = mean_se, geom = "point", size = 5, 
               position = position_dodge(.3))+
  theme_bw()+facet_wrap(~first_sec)+
  labs(title = "first vs second blocks Partner + Choice")

dat_clean %>% 
  group_by(participant) %>%
    group_by(participant, Block.thisN) %>%
  mutate(good_trials_n = n()) %>%
  filter(good_trials_n > 8) %>%
  ggplot(aes(y = sync_value, x = Block.thisN, color = Partner))+
  geom_smooth(method = "lm")+
  theme_bw()

```


```{r}

dat_clean = dat_clean %>%
  group_by(participant) %>%
  mutate(
    avg_resp = (RTLeft+RTRight)/2
    ) %>%
  group_by(participant, Partner) %>%
  mutate(
    sync_val_computer = abs((avg_resp-Number))/
      (avg_resp + Number)*100
    ) %>%
  mutate(
    reSync_value = ifelse(Partner == "Computer", sync_val_computer, 
                               ifelse(Partner == "Human", sync_value, NA)
                               )
         ) 

dat_clean %>% group_by(Partner) %>%
  summarize(reSync_value = mean(reSync_value),
            sync_value = mean(sync_value),
            sync_val_computer = mean(sync_val_computer))

dat_clean %>% group_by(participant, Block.thisN) %>%
  mutate(good_trials_n = n()) %>%
  filter(good_trials_n > 8) %>%
  ungroup(Block.thisN) %>%
ggplot(aes(y = reSync_value, Partner, color = choice)) +
    stat_summary(fun.data = mean_se, geom = "errorbar", 
               width = .1, position = position_dodge(.3),
               fun.args = list(mult = 1))+
  stat_summary(fun.data = mean_se, geom = "point", size = 5, 
               position = position_dodge(.3))+theme_bw()
  #facet_wrap(~participant, scales = "free_y")
  
```

  